"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Francisco C. Ossa"
email = "francisco@oza.cl"
key = "9240DDAE84B1400A"

[ui]
default-command = "log"

[signing]
behavior = "drop"
backend = "gpg"
key = "9240DDAE84B1400A"

[git]
sign-on-push = true
