"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Francisco C. Ossa"
email = "fraco_oxza@outlook.com"

[ui]
default-command = "log"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
merge-editor = "vimdiff"

[merge-tools.vimdiff]
merge-args = ["-f", "-d", "$output", "-M",
    "$left", "$base", "$right",
    "-c", "wincmd J", "-c", "set modifiable",
    "-c", "set write"]
program = "nvim"
merge-tool-edits-conflict-markers = true    # See below for an explanation

[signing]
behavior = "drop"
backend = "gpg"

[git]
sign-on-push = true
