"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Francisco C. Ossa"
email = "fraco_oxza@outlook.com"

[ui]
default-command = "log"

[signing]
behavior = "drop"
backend = "gpg"

[git]
sign-on-push = true
