#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[revset-aliases]
"trunk()" = "main@origin"

[user]
email = "fcarvajal@kimengames.com"

[signing]
key = "/home/fraco/.ssh/id_ed25519"
backend = "ssh"
